# Generated by Django 5.0.6 on 2024-08-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
