# Generated by Django 5.0.6 on 2024-08-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_valid_from_profile_valid_till'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='valid_till',
        ),
    ]
