# Generated by Django 5.0.6 on 2024-08-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_valid_from_remove_profile_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
